title: Gwanda Blitz
author: Trang H.
email: tranglake@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Helloooo
theme: minima
# social links
twitter_username: trangh09 # DO NOT include the @ character, or else the build will fail!
github_username:  trangh09 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
